name: Windows cross build with MXE

on:
  push:
    branches:
      - master
      - release-**
    paths:
    - 'src/**'
    - 'external/**'
    - 'python/**'
    - 'tests/**'
    - 'ms-windows/**'
    - 'CMakeLists.txt'
    - '.github/workflows/mxe.yml'
  pull_request:
    branches:
      - master
      - release-**
    paths:
    - 'src/**'
    - 'external/**'
    - 'python/**'
    - 'tests/**'
    - 'ms-windows/**'
    - 'CMakeLists.txt'
    - '.github/workflows/mxe.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cross build with MXE
      run: cd $GITHUB_WORKSPACE && ms-windows/mxe/build.sh
    - name: Rename artifact
      run: cd $GITHUB_WORKSPACE && mv qgis-mxe-release-*.zip qgis-mxe-release.zip
    - name: Upload build
      uses: actions/upload-artifact@v2.2.3
      with:
        name: QGIS for Windows 64bit
        path: qgis-mxe-release.zip

